export const data = [
  {
    id: 1,
    boardName: 'Development',
    categories: ['todo', 'doing', 'done'],
    tasks: [
      {
        id: 1,
        task: 'Live Chatbot App',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
        createdAt: 'Feb 09',
      },

      {
        id: 2,
        task: 'Live Chatbot App',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
        createdAt: 'Feb 09',
      },
      {
        id: 3,
        task: 'Live Chatbot App',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
        createdAt: 'Feb 09',
      },
      {
        id: 4,
        task: 'Live Chatbot App',
        category: 'todo',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        createdAt: 'Feb 09',
      },
      {
        id: 5,
        task: 'Search Filter',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
        createdAt: 'Feb 09',
      },
      {
        id: 6,
        task: 'Search Filter',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
        createdAt: 'Feb 09',
      },
      {
        id: 7,
        task: 'Search Filter',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
        createdAt: 'Feb 09',
      },
      {
        id: 8,
        task: 'Search Filter',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
        createdAt: 'Feb 09',
      },
      {
        id: 9,
        task: 'Authorization',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
        createdAt: 'Feb 09',
      },
      {
        id: 10,
        task: 'Authorization',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
        createdAt: 'Feb 09',
      },
      {
        id: 11,
        task: 'Authorization',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
        createdAt: 'Feb 09',
      },
      {
        id: 12,
        task: 'Authorization',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
        createdAt: 'Feb 09',
      },
    ],
  },
  {
    id: 2,
    boardName: 'UI Design',
    categories: ['todo', 'doing', 'done'],
    tasks: [
      {
        id: 1,
        task: 'Add Project page',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
        createdAt: 'Feb 09',
      },
      {
        id: 2,
        task: 'Add Project page',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
        createdAt: 'Feb 09',
      },
      {
        id: 3,
        task: 'Add Project page',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
        createdAt: 'Feb 09',
      },
      {
        id: 4,
        task: 'Add Project page',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
        createdAt: 'Feb 09',
      },
      {
        id: 5,
        task: 'Fix photos quality',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
        createdAt: 'Feb 09',
      },
      {
        id: 6,
        task: 'Fix photos quality',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
        createdAt: 'Feb 09',
      },
      {
        id: 7,
        task: 'Fix photos quality',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
        createdAt: 'Feb 09',
      },
      {
        id: 8,
        task: 'Fix photos quality',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
        createdAt: 'Feb 09',
      },
      {
        id: 9,
        task: 'New animations',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
        createdAt: 'Feb 09',
      },
      {
        id: 10,
        task: 'New animations',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
        createdAt: 'Feb 09',
      },
      {
        id: 11,
        task: 'New animations',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
        createdAt: 'Feb 09',
      },
      {
        id: 12,
        task: 'New animations',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
        createdAt: 'Feb 09',
      },
    ],
  },
];
