export const data = [
  {
    id: 1,
    boardName: 'Development',
    tasks: [
      {
        id: 1,
        task: 'Live Chatbot App',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
      },
      {
        id: 2,
        task: 'Live Chatbot App',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
      },
      {
        id: 3,
        task: 'Live Chatbot App',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
      },
      {
        id: 4,
        task: 'Live Chatbot App',
        category: 'todo',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
      },
      {
        id: 5,
        task: 'Search Filter',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
      },
      {
        id: 6,
        task: 'Search Filter',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
      },
      {
        id: 7,
        task: 'Search Filter',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
      },
      {
        id: 8,
        task: 'Search Filter',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
      },
      {
        id: 9,
        task: 'Authorization',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
      },
      {
        id: 10,
        task: 'Authorization',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
      },
      {
        id: 11,
        task: 'Authorization',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
      },
      {
        id: 12,
        task: 'Authorization',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
      },
    ],
  },
  {
    id: 2,
    boardName: 'UI Design',
    tasks: [
      {
        id: 1,
        task: 'Live Chatbot App',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
      },
      {
        id: 2,
        task: 'Live Chatbot App',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
      },
      {
        id: 3,
        task: 'Live Chatbot App',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
      },
      {
        id: 4,
        task: 'Live Chatbot App',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'todo',
      },
      {
        id: 5,
        task: 'Search Filter',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
      },
      {
        id: 6,
        task: 'Search Filter',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
      },
      {
        id: 7,
        task: 'Search Filter',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
      },
      {
        id: 8,
        task: 'Search Filter',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'doing',
      },
      {
        id: 9,
        task: 'Authorization',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
      },
      {
        id: 10,
        task: 'Authorization',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
      },
      {
        id: 11,
        task: 'Authorization',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
      },
      {
        id: 12,
        task: 'Authorization',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, similique.',
        category: 'done',
      },
    ],
  },
];
