export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const OPEN_ADD_BOARD = 'OPEN_ADD_BOARD';
export const HANDLE_ADD_BOARD = 'HANDLE_ADD_BOARD';
export const SET_FILTERED_BOARD = 'SET_FILTERED_BOARD';
